// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.example;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_SendMessageReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_SendMessageReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_GetMessagesRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_GetMessagesRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\013com.example\"\007\n\005Empty\"!\n\016Se" +
      "ndMessageReq\022\017\n\007message\030\001 \001(\t\"\"\n\016GetMess" +
      "agesRes\022\020\n\010messages\030\001 \003(\t2\221\001\n\013DemoServic" +
      "e\022@\n\013sendMessage\022\033.com.example.SendMessa" +
      "geReq\032\022.com.example.Empty\"\000\022@\n\013getMessag" +
      "es\022\022.com.example.Empty\032\033.com.example.Get" +
      "MessagesRes\"\000B\025\n\013com.exampleB\004DemoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_SendMessageReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_SendMessageReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_SendMessageReq_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_example_GetMessagesRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_GetMessagesRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_GetMessagesRes_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
