// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.example;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.Empty)
    com.google.protobuf.MessageOrBuilder {
}
