// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.example;

public interface SendMessageReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.SendMessageReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
